### ISSUE TITLE
Update Web Install instructions for thunderbird.desktop

### ISSUE THREAD

**Issue by postnick** [mozilla/sumo-kb#1]
The instructions on the website have a link that no longer works and will need to be linked to this file.  Can you correct instructions? I'm not sure who owns this page. 

https://support.mozilla.org/en-US/kb/installing-thunderbird-linux#w_installing-thunderbird-manually-for-advanced-users

![Screenshot from 2022-06-30 17-12-30](https://user-images.githubusercontent.com/8466253/176787513-e9cf8b30-54d1-408a-a71b-deade28a6256.png)

**Comment by dannycolin** [comment]
Fixed in [revision 247091](https://support.mozilla.org/en-US/kb/installing-thunderbird-linux/revision/247091). Should go live in the next 24hrs.

Thanks for the report :)

**Comment by dannycolin** [comment]
Closing since it's now live on the production website.
